import { Providers } from "../redux/provider"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }) {
    return (
      <html lang="en">
        <Providers>
        <body>{children}</body>
        </Providers>
      </html>
    )
  }
  